<?php
$_scarabConfig = Mage::getStoreConfig('scarab_research/general');
$_scarabConfigw = Mage::getStoreConfig('scarab_research/widgets');
?> 
<?php if($_scarabConfig['enabled']) { ?>
<?php if($_scarabConfigw['scarabproduct']) { ?>
<div id="my-recommendation-container"></div>
<script>
Scarab.recommend('RELATED', 'my-recommendation-container', <?php echo $_scarabConfigw['scarabproductcount']; ?>);
</script>
<?php }
if($_scarabConfigw['scarabproduct2']) { ?>
<div id="my-recommendation-container2"></div>
<script>
Scarab.recommend('ALSO_VIEWED', 'my-recommendation-container2', <?php echo $_scarabConfigw['scarabproductcount2']; ?>);
</script>
<?php }
 } ?>