<?php $_scarabConfig = Mage::getStoreConfig('scarab_research/general'); 
if($_scarabConfig['enabled']) { 
if($this->getData('itemnumber')) {
$itemnumber = $this->getData('itemnumber');
} else {
$itemnumber = 4;
}
?>
<script type="text/html" id="my-recommender-template3" >
<![CDATA[
{{ if(SC.page.products.length) { }}
<div class="scarab-itemlist">
    <div class="scarab-prev">?</div>
    {{ for(var i=0;i<SC.page.p
roducts.length;i++) { }}
    <span data-scarabitem="{{= SC.page.products[i].id }}" class="scarab-item">
        <a href="{{= SC.page.products[i].link }}">
            <img src="{{= SC.page.products[i].image }}">
            {{= SC.page.products[i].title }}
        </a>
    </span>
    {{ } }}
    <div class="scarab-next">?</div>
</div>
{{ } }}
]]>
</script>
<div id="my-recommendation-container3"></div>
<script>
Scarab.recommend('PERSONAL', 'my-recommendation-container3', <?php echo $itemnumber; ?>,document.getElementById('my-recommender-template3').innerHTML);
</script>
<?php } ?>