<?php
$_scarabConfig = Mage::getStoreConfig('scarab_research/general');
$_scarabConfigw = Mage::getStoreConfig('scarab_research/widgets');
?>     
<?php if($_scarabConfig['enabled']) { ?>
<?php $product_ids = Mage::getModel('checkout/cart')->getProductIds(); ?>
<script>
<?php foreach($product_ids as $pid): ?>
<?php echo "Scarab.cartItem('".$pid."');"; ?>
 <?php endforeach ?>
</script>
<?php if($_scarabConfigw['scarabcheckout']) { ?>
<div id="my-recommendation-container"></div>
<script>
Scarab.recommend('CART', 'my-recommendation-container', <?php echo $_scarabConfigw['scarabcheckoutcount']; ?>);
</script>
<?php }
if($_scarabConfigw['scarabcheckout2']) { ?>
<div id="my-recommendation-container2"></div>
<script>
Scarab.recommend('PERSONAL_RECENT', 'my-recommendation-container2', <?php echo $_scarabConfigw['scarabcheckoutcount2']; ?>);
</script>
<?php }
} ?>

