<?php
$_scarabConfig = Mage::getStoreConfig('scarab_research/general');
?>     
<?php if($_scarabConfig['general']) { ?>
<?php if($_scarabConfig['scarabcheckout']) { ?>
<div id="my-recommendation-container"></div>
<script>
<?php foreach($this->getItems() as $_item): ?>
<?php echo "Scarab.cartItem('".$_item->getProductId()."');"; ?>
 <?php endforeach ?>
</script>
<script>
Scarab.recommend('CART', 'my-recommendation-container', <?php echo $_scarabConfig['scarabcheckoutcount']; ?>);
</script>
<?php }
if($_scarabConfig['scarabcheckout2']) { ?>
<div id="my-recommendation-container2"></div>
<script>
<?php foreach($this->getItems() as $_item): ?>
<?php echo "Scarab.cartItem('".$_item->getProductId()."');"; ?>
 <?php endforeach ?>
</script>
<script>
Scarab.recommend('PERSONAL', 'my-recommendation-container2', <?php echo $_scarabConfig['scarabcheckoutcount2']; ?>);
</script>
<?php }
} ?>

